#!/usr/bin/env bash

if [ "$1" == "" ]; then
	export COFFEA_IMAGE=coffeateam/coffea-dask-almalinux8:2024.5.0-py3.11
else
	export COFFEA_IMAGE=$1
fi

echo "Coffea Image: ${COFFEA_IMAGE}"

EXTERNAL_BIND=${PWD} singularity exec -B /etc/condor -B /eos -B /afs -B /cvmfs --pwd ${PWD} \
	/cvmfs/unpacked.cern.ch/registry.hub.docker.com/${COFFEA_IMAGE} \
	/bin/bash --rcfile /srv/.bashrc
